title:            Hsming
description:      Blog.
url:              http://hsming.github.io
signoff:          hsming
disqus_shortname: hsming
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: 'UA-43973459-1'

links:
  - name:         Blog
    url:          http://hsming.github.io
  - name:         About
    url:          /about
  - name:         Email
    url:          mailto:hsming06@gmail.com
    external:     true
  - name:         GitHub
    url:          http://github.com/hsming
    external:     true
  - name:         Twitter
    url:          https://twitter.com/hshaoming
    external:     true
pygments:         true
permalink:        pretty
markdown:         rdiscount
rdiscount:
  extensions:     [smart]